### ISSUE TITLE
Reporte de práctica animación objeto 3D en Blender

### ISSUE THREAD

**Issue by JulioCesar69** [SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-team-pc-box#1]
[Practica animación.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-team-pc-box/files/8348092/Practica.animacion.pdf)

**Comment by ThorSampy** [comment]
El trabajo esta bien echo y cuenta con los puntos establecidos: calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...pueden pasar el link...
